openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API для управління контактами
tags:
  - name: Contacts
    description: Contact management endpoints
servers:
  - url: http://localhost:3000
  - url: #посилання на задеплоєний сайт
paths:
  /contacts/{contactId}:
    $ref: '../swagger/paths/contacts/{id}/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
