openapi: 3.0.0
info:
  version: 1.0.0
  title: Contacts API
  description: API management endpoints
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-contacts-i3qb.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'

  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/contactid/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/contactid/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/contactid/delete.yaml'

components:
  schemas:
    Contact:
      $ref: '../swagger/components/schemas/Contact.yaml'
    ErrorResponse:
      $ref: '../swagger/components/schemas/ErrorResponse.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
